# Generated by Django 5.0.4 on 2025-12-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_stripecustomer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('next_access', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
