"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import os
import environ



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# django-environで複数行のキーを扱えるようにする
env = environ.Env(multiline=True)
env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = ['cybernetcall.onrender.com', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://cybernetcall.onrender.com']

# または、デバッグモードの時だけ許可するという方法もあります
if DEBUG:
    ALLOWED_HOSTS.extend(['.ngrok-free.app', '.onrender.com'])

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cnc',
    'signaling', # WebSocketシグナリング用アプリを追加
    'channels', # Django Channels を追加
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'cnc.middleware.ServiceWorkerAllowedHeaderMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Renderのようなリバースプロキシ環境で、httpsを正しく認識させるための設定
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'cybernetcall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "cybernetcall.asgi.application"
WSGI_APPLICATION = 'cybernetcall.wsgi.application'

# RedisのURLをsettingsで定義
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')

if DEBUG:
    # 開発環境ではRedis不要のインメモリチャネルレイヤーを使用
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    # 本番環境ではRedisを使用
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# ↓ 追加
# default_dburl = "sqlite:///" + str(BASE_DIR / "db.sqlite3")

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# 開発環境(DEBUG=True)ではSQLiteを、本番環境(DEBUG=False)ではDATABASE_URLを使用する
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    default_db = env.db('DATABASE_URL')
    # SupabaseのURLに含まれる ?pgbouncer=true オプションはpsycopg2でエラーになるため削除
    if 'OPTIONS' in default_db and 'pgbouncer' in default_db['OPTIONS']:
        del default_db['OPTIONS']['pgbouncer']

    DATABASES = {
        'default': default_db
    }
    # Supabase Transaction Mode (port 6543) 対策
    # URL末尾に ?pgbouncer=true がない場合でも、ここで強制的にPrepared Statementsを無効化する
    if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
        DATABASES['default'].setdefault('DISABLE_SERVER_SIDE_CURSORS', True)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS は、アプリケーションの 'static' ディレクトリ外に静的ファイルを置く場合に使用します。
# 今回は 'cnc' アプリ内に静的ファイルがあるため、この設定は不要です。


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

STATIC_ROOT = str(BASE_DIR / "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SUPERUSER_NAME = env("SUPERUSER_NAME", default=None)
SUPERUSER_EMAIL = env("SUPERUSER_EMAIL", default=None)
SUPERUSER_PASSWORD = env("SUPERUSER_PASSWORD", default=None)

VAPID_PUBLIC_KEY = env("VAPID_PUBLIC_KEY", default=None)
VAPID_PRIVATE_KEY = env("VAPID_PRIVATE_KEY", default=None)

STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default=None)
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default=None)
STRIPE_PRICE_ID_USD = env("STRIPE_PRICE_ID_USD", default=None)
STRIPE_PRICE_ID_JPY = env("STRIPE_PRICE_ID_JPY", default=None)
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default=None)
